compressionLevel: mixed
enableGlobalCache: false
nmHoistingLimits: workspaces
nodeLinker: pnp

pnpUnpluggedFolder: ./.yarn/unplugged
pnpMode: loose


packageExtensions:
  "debug@*":
    dependencies:
      supports-color: "*"